version: '3'
services:
  eesampling:
    build: .
    image: eesampling
    entrypoint: eesampling
    volumes:
      - .:/app
      - /tmp:/tmp
    env_file:
      - dev-env.env

  test:
    image: eesampling
    entrypoint: py.test
    volumes:
      - .:/app

  blacken:
    image: eesampling
    entrypoint: black .
    volumes:
      - .:/app

  docs:
    image: eesampling
    ports:
      - "${HOST_PORT_DOCS:-8000}:8000"
    entrypoint: make -C docs livehtml
    volumes:
      - .:/app

  fury:
    image: eesampling
    entrypoint: python setup.py sdist upload -r fury
    volumes:
      - .:/app
